# 基于几何深度学习的四边形化模式检索框架配置
# Configuration for geometric deep learning quadrangulation pattern retrieval framework

data:
  root: "./data"  # 数据根目录
  train_mesh: "./model/new/artist1-torso-newui.obj" # 训练用几何查询源
  val_mesh: "./model/new/artist2-hand-newui.obj" # 验证用几何查询源
  
model:
  anchor_in_channels: 8    # 锚点特征维度 (6拓扑+2几何)
  pattern_in_channels: 6   # 模式特征维度 (6拓扑)
  hidden_channels: 128     # 隐藏层维度
  out_channels: 64        # 输出嵌入维度
  gnn_type: "gat"         # GNN类型: gcn/gat/graphsage

training:
  epochs: 100
  learning_rate: 0.001
  batch_size: 32
  margin: 1.0             # 三元组损失边界
  num_triplets_train: 1000  # 训练三元组数量
  num_triplets_val: 200     # 验证三元组数量
  checkpoint_dir: "./checkpoints"

evaluation:
  recall_k: [1, 5, 10]    # Recall@K评估指标
